<?php $this->headTitle('Edit User'); ?>
<h1><?php echo $this->escapeHtml('Edit User'); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'edit', 'id'     => $this->id)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="row">
	<?php echo $this->formLabel($form->get('firstname')); ?>
	<?php echo $this->formElement($form->get('firstname')); ?>
	<?php echo $this->formElementErrors($form->get('firstname')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('lastname')); ?>
	<?php echo $this->formElement($form->get('lastname')); ?>
	<?php echo $this->formElementErrors($form->get('lastname')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('email')); ?>
	<?php echo $this->formElement($form->get('email')); ?>
	<?php echo $this->formElementErrors($form->get('email')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('username')); ?>
	<?php echo $this->formElement($form->get('username')); ?>
	<?php echo $this->formElementErrors($form->get('username')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('algorithm')); ?>
	<?php echo $this->formElement($form->get('algorithm')); ?>
	<?php echo $this->formElementErrors($form->get('algorithm')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('salt')); ?>
	<?php echo $this->formElement($form->get('salt')); ?>
	<?php echo $this->formElementErrors($form->get('salt')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('password')); ?>
	<?php echo $this->formElement($form->get('password')); ?>
	<?php echo $this->formElementErrors($form->get('password')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('application_id')); ?>
	<?php echo $this->formElement($form->get('application_id')); ?>
	<?php echo $this->formElementErrors($form->get('application_id')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('application_type_id')); ?>
	<?php echo $this->formElement($form->get('application_type_id')); ?>
	<?php echo $this->formElementErrors($form->get('application_type_id')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('is_active')); ?>
	<?php echo $this->formElement($form->get('is_active')); ?>
	<?php echo $this->formElementErrors($form->get('is_active')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('is_super_admin')); ?>
	<?php echo $this->formElement($form->get('is_super_admin')); ?>
	<?php echo $this->formElementErrors($form->get('is_super_admin')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('last_login')); ?>
	<?php echo $this->formElement($form->get('last_login')); ?>
	<?php echo $this->formElementErrors($form->get('last_login')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('created_at')); ?>
	<?php echo $this->formElement($form->get('created_at')); ?>
	<?php echo $this->formElementErrors($form->get('created_at')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('updated_at')); ?>
	<?php echo $this->formElement($form->get('updated_at')); ?>
	<?php echo $this->formElementErrors($form->get('updated_at')); ?>
</div>

<div class="row">
	<?php echo $this->formLabel($form->get('deleted')); ?>
	<?php echo $this->formElement($form->get('deleted')); ?>
	<?php echo $this->formElementErrors($form->get('deleted')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
