<?php $this->headTitle('Students'); ?>
<h1><?php echo $this->escapeHtml('Students'); ?></h1>
<p><a href="<?php echo $this->url('student', array('action'=>'add'));?>">Add new studnet</a></p>
<table class="table  table-striped">
<tr>
<td>Id</td>
<td>Firstname</td>
<td>Lastname</td>
<td>Actions</td>
</tr>
<?php foreach($students as $user) : ?>
<tr>
<td><?php echo $this->escapeHtml($user->getId());?></td>
<td><?php echo $this->escapeHtml($user->getFirstName());?></td>
<td><?php echo $this->escapeHtml($user->getLastName());?></td>
<td><a href="<?php echo $this->url('user',array('action'=>'edit', 'id' => $user->getId()));?>">Edit</a>
<a href="<?php echo $this->url('user',array('action'=>'delete', 'id' => $user->getId()));?>">Delete</a></td>
</tr>
<?php endforeach; ?>
</table>

