<?php $this->headTitle('Students'); ?>
<h1><?php echo $this->escapeHtml('Students'); ?></h1>
<p><a href="<?php echo $this->url('student', array('action'=>'add'));?>">Add new student</a></p>
<table class="table  table-striped">
<tr>
<td>Id</td>
<td>Student Id</td>
<td>First Name</td>
<td>Last Name</td>
<td>Class</td>
<td>Actions</td>
</tr>
<?php foreach($students as $user) : ?>
<tr>
<td><?php echo $this->escapeHtml($user->getId());?></td>
<td><?php echo $this->escapeHtml($user->getStudentId());?></td>
<td><?php echo $this->escapeHtml($user->getFirstName());?></td>
<td><?php echo $this->escapeHtml($user->getLastName());?></td>
<td><?php echo $this->escapeHtml($user->getClass()->getName());?></td>
<td><a href="<?php echo $this->url('student',array('action'=>'edit', 'id' => $user->getId()));?>">Edit</a>
<a href="<?php echo $this->url('student',array('action'=>'delete', 'id' => $user->getId()));?>">Delete</a>
<a href="<?php echo $this->url('student',array('action'=>'marks', 'id' => $user->getId()));?>">Marks</a>

</td>
</tr>
<?php endforeach; ?>
</table>

